### ISSUE TITLE
AttributeError for certain key combinations with MinutesMenu

### ISSUE THREAD

**Issue by jhanarato** [jhanarato/visual-timer#1]
When playing around with the timer I noticed it would crash while displaying the minutes menu. I managed to reproduce the problem with this stack trace:

```
Traceback (most recent call last):
  File "code.py", line 14, in <module>
  File "/lib/meditation_timer.py", line 21, in perform_sequence
  File "/lib/meditation_timer.py", line 44, in select_minutes
AttributeError: 'NoneType' object has no attribute 'integer_value'
```
The code in question:
```python
    def select_minutes(self):
        menu = MinutesMenu()
        menu.light_all_option_keys()
        menu.wait_for_selection()
        # At this point something should be selected and get_selected() returns something.
        menu.display_selection()

        pause = Pause(seconds=1.5)
        pause.wait_until_complete()

        # BUG: With some key combinations get_selected() returns None.
        return menu.get_selected().integer_value
```
Perhaps what happens is this:

1. An active selection button is pressed and a choice is made.
2. There is a pause.
3. During the pause the user presses an unassigned button and the selection becomes `None`. 
4. Once the pause is complete we attempt to retrieve `integer_value` but `get_selected()` returns `None`

**Comment by jhanarato** [comment]
A quick test shows this problem is reproducible:

1. Start and press the red key
2. Within a second press an unlit key.
3. An exception is thrown.

Note that debounce is 0.125 seconds and hold is 0.75 seconds so each press needs to be for that span of time.

**Comment by jhanarato** [comment]
A quick fix in the end:

```python
    def _set_selected(self, key_num):
        if key_num in self._options:
            self._selected = self._options.get(key_num)
```
Check that the selected key is one of the options before setting.

**Comment by jhanarato** [comment]
I managed to reintroduce the same bug. Here's the stack trace:

```
Traceback (most recent call last):
  File "code.py", line 427, in <module>
  File "code.py", line 26, in perform_sequence
  File "code.py", line 74, in get_users_choice
AttributeError: 'NoneType' object has no attribute 'value'
```

In general it might be better to return a default value rather than None.

**Comment by jhanarato** [comment]
Fixed the bug. Still need to look at alternatives to returning `None`.
