### ISSUE TITLE
Avoid returning `None`

### ISSUE THREAD

**Issue by jhanarato** [jhanarato/visual-timer#6]
Having been stung by the [billion dollar mistake](https://en.wikipedia.org/wiki/Tony_Hoare#Apologies_and_retractions) a couple of times now (issue #1) it might be a good swap `None` for a sensible default where possible. For instance, return key number -1 instead in `MenuSelectionHandler`. In that case we're still going to get an exception down the line, `KeyError` probably, but it's a good practice to develop.

**Comment by jhanarato** [comment]
`Menu` and `MenuSelectionHandler` use `Menu.NO_SELECTION` rather than None. 

`Hardware` still uses it, but we can deal with that when we remove the entire Hardware class as per issue #5.

**Comment by jhanarato** [comment]
And it's cropped up again.

When pressing a non-option key on the minute's menu before making a selection this happens:
```python
Traceback (most recent call last):
  File "code.py", line 348, in <module>
  File "code.py", line 31, in main_sequence
  File "code.py", line 61, in get_users_choice
  File "code.py", line 140, in display_selection
AttributeError: 'NoneType' object has no attribute 'key_num'
```

**Comment by jhanarato** [comment]
Menu.fill_missing_options() should solve the problem.
